import torch
from torch.nn import Conv2d, BatchNorm2d, SiLU, Sigmoid, AdaptiveAvgPool2d, Softmax, Dropout, Linear, ReLU, BatchNorm1d, MaxPool2d
from torchvision.ops import StochasticDepth

cnn_layers = [
    (Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1)), 'conv1 (Conv2d)') ,
    (MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False), 'pool1 (MaxPool2d)') ,
    (Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1)), 'conv2 (Conv2d)') ,
    (MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False), 'pool2 (MaxPool2d)') ,
    (Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1)), 'conv3 (Conv2d)') ,
    (MaxPool2d(kernel_size=2, stride=2, padding=0, dilation=1, ceil_mode=False), 'pool3 (MaxPool2d)') ,
    (Linear(in_features=43264, out_features=128, bias=True), 'f1 (Linear)') ,
    (Linear(in_features=128, out_features=128, bias=True), 'f2 (Linear)') ,
    (Linear(in_features=128, out_features=53, bias=True), 'f3 (Linear)') ,
]

efficientnet1_layers = [
    (Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False), 'base_model.features.0.0 (Conv2d)') ,
    (BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.0.2 (SiLU)') ,
    (Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False), 'base_model.features.1.0.block.0.0 (Conv2d)') ,
    (BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.1.0.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.1.0.block.0.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.1.0.block.1.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(32, 8, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.1.0.block.1.fc1 (Conv2d)') ,
    (Conv2d(8, 32, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.1.0.block.1.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.1.0.block.1.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.1.0.block.1.scale_activation (Sigmoid)') ,
    (Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.1.0.block.2.0 (Conv2d)') ,
    (BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.1.0.block.2.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.0, mode='row'), 'base_model.features.1.0.stochastic_depth (StochasticDepth)') ,
    (Conv2d(16, 96, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.2.0.block.0.0 (Conv2d)') ,
    (BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.2.0.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.2.0.block.0.2 (SiLU)') ,
    (Conv2d(96, 96, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=96, bias=False), 'base_model.features.2.0.block.1.0 (Conv2d)') ,
    (BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.2.0.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.2.0.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.2.0.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(96, 4, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.2.0.block.2.fc1 (Conv2d)') ,
    (Conv2d(4, 96, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.2.0.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.2.0.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.2.0.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(96, 24, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.2.0.block.3.0 (Conv2d)') ,
    (BatchNorm2d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.2.0.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.0125, mode='row'), 'base_model.features.2.0.stochastic_depth (StochasticDepth)') ,
    (Conv2d(24, 144, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.2.1.block.0.0 (Conv2d)') ,
    (BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.2.1.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.2.1.block.0.2 (SiLU)') ,
    (Conv2d(144, 144, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=144, bias=False), 'base_model.features.2.1.block.1.0 (Conv2d)') ,
    (BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.2.1.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.2.1.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.2.1.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(144, 6, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.2.1.block.2.fc1 (Conv2d)') ,
    (Conv2d(6, 144, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.2.1.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.2.1.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.2.1.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(144, 24, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.2.1.block.3.0 (Conv2d)') ,
    (BatchNorm2d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.2.1.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.025, mode='row'), 'base_model.features.2.1.stochastic_depth (StochasticDepth)') ,
    (Conv2d(24, 144, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.3.0.block.0.0 (Conv2d)') ,
    (BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.3.0.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.3.0.block.0.2 (SiLU)') ,
    (Conv2d(144, 144, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2), groups=144, bias=False), 'base_model.features.3.0.block.1.0 (Conv2d)') ,
    (BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.3.0.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.3.0.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.3.0.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(144, 6, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.3.0.block.2.fc1 (Conv2d)') ,
    (Conv2d(6, 144, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.3.0.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.3.0.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.3.0.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(144, 40, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.3.0.block.3.0 (Conv2d)') ,
    (BatchNorm2d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.3.0.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.037500000000000006, mode='row'), 'base_model.features.3.0.stochastic_depth (StochasticDepth)') ,
    (Conv2d(40, 240, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.3.1.block.0.0 (Conv2d)') ,
    (BatchNorm2d(240, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.3.1.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.3.1.block.0.2 (SiLU)') ,
    (Conv2d(240, 240, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=240, bias=False), 'base_model.features.3.1.block.1.0 (Conv2d)') ,
    (BatchNorm2d(240, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.3.1.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.3.1.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.3.1.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(240, 10, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.3.1.block.2.fc1 (Conv2d)') ,
    (Conv2d(10, 240, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.3.1.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.3.1.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.3.1.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(240, 40, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.3.1.block.3.0 (Conv2d)') ,
    (BatchNorm2d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.3.1.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.05, mode='row'), 'base_model.features.3.1.stochastic_depth (StochasticDepth)') ,
    (Conv2d(40, 240, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.4.0.block.0.0 (Conv2d)') ,
    (BatchNorm2d(240, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.0.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.0.block.0.2 (SiLU)') ,
    (Conv2d(240, 240, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=240, bias=False), 'base_model.features.4.0.block.1.0 (Conv2d)') ,
    (BatchNorm2d(240, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.0.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.0.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.4.0.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(240, 10, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.4.0.block.2.fc1 (Conv2d)') ,
    (Conv2d(10, 240, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.4.0.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.0.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.4.0.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(240, 80, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.4.0.block.3.0 (Conv2d)') ,
    (BatchNorm2d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.0.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.0625, mode='row'), 'base_model.features.4.0.stochastic_depth (StochasticDepth)') ,
    (Conv2d(80, 480, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.4.1.block.0.0 (Conv2d)') ,
    (BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.1.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.1.block.0.2 (SiLU)') ,
    (Conv2d(480, 480, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=480, bias=False), 'base_model.features.4.1.block.1.0 (Conv2d)') ,
    (BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.1.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.1.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.4.1.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(480, 20, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.4.1.block.2.fc1 (Conv2d)') ,
    (Conv2d(20, 480, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.4.1.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.1.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.4.1.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(480, 80, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.4.1.block.3.0 (Conv2d)') ,
    (BatchNorm2d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.1.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.07500000000000001, mode='row'), 'base_model.features.4.1.stochastic_depth (StochasticDepth)') ,
    (Conv2d(80, 480, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.4.2.block.0.0 (Conv2d)') ,
    (BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.2.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.2.block.0.2 (SiLU)') ,
    (Conv2d(480, 480, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=480, bias=False), 'base_model.features.4.2.block.1.0 (Conv2d)') ,
    (BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.2.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.2.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.4.2.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(480, 20, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.4.2.block.2.fc1 (Conv2d)') ,
    (Conv2d(20, 480, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.4.2.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.2.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.4.2.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(480, 80, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.4.2.block.3.0 (Conv2d)') ,
    (BatchNorm2d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.2.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.08750000000000001, mode='row'), 'base_model.features.4.2.stochastic_depth (StochasticDepth)') ,
    (Conv2d(80, 480, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.5.0.block.0.0 (Conv2d)') ,
    (BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.0.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.0.block.0.2 (SiLU)') ,
    (Conv2d(480, 480, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=480, bias=False), 'base_model.features.5.0.block.1.0 (Conv2d)') ,
    (BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.0.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.0.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.5.0.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(480, 20, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.5.0.block.2.fc1 (Conv2d)') ,
    (Conv2d(20, 480, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.5.0.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.0.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.5.0.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(480, 112, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.5.0.block.3.0 (Conv2d)') ,
    (BatchNorm2d(112, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.0.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.1, mode='row'), 'base_model.features.5.0.stochastic_depth (StochasticDepth)') ,
    (Conv2d(112, 672, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.5.1.block.0.0 (Conv2d)') ,
    (BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.1.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.1.block.0.2 (SiLU)') ,
    (Conv2d(672, 672, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=672, bias=False), 'base_model.features.5.1.block.1.0 (Conv2d)') ,
    (BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.1.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.1.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.5.1.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(672, 28, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.5.1.block.2.fc1 (Conv2d)') ,
    (Conv2d(28, 672, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.5.1.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.1.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.5.1.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(672, 112, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.5.1.block.3.0 (Conv2d)') ,
    (BatchNorm2d(112, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.1.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.1125, mode='row'), 'base_model.features.5.1.stochastic_depth (StochasticDepth)') ,
    (Conv2d(112, 672, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.5.2.block.0.0 (Conv2d)') ,
    (BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.2.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.2.block.0.2 (SiLU)') ,
    (Conv2d(672, 672, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=672, bias=False), 'base_model.features.5.2.block.1.0 (Conv2d)') ,
    (BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.2.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.2.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.5.2.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(672, 28, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.5.2.block.2.fc1 (Conv2d)') ,
    (Conv2d(28, 672, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.5.2.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.2.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.5.2.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(672, 112, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.5.2.block.3.0 (Conv2d)') ,
    (BatchNorm2d(112, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.2.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.125, mode='row'), 'base_model.features.5.2.stochastic_depth (StochasticDepth)') ,
    (Conv2d(112, 672, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.6.0.block.0.0 (Conv2d)') ,
    (BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.0.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.0.block.0.2 (SiLU)') ,
    (Conv2d(672, 672, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2), groups=672, bias=False), 'base_model.features.6.0.block.1.0 (Conv2d)') ,
    (BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.0.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.0.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.6.0.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(672, 28, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.6.0.block.2.fc1 (Conv2d)') ,
    (Conv2d(28, 672, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.6.0.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.0.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.6.0.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(672, 192, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.6.0.block.3.0 (Conv2d)') ,
    (BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.0.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.1375, mode='row'), 'base_model.features.6.0.stochastic_depth (StochasticDepth)') ,
    (Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.6.1.block.0.0 (Conv2d)') ,
    (BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.1.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.1.block.0.2 (SiLU)') ,
    (Conv2d(1152, 1152, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=1152, bias=False), 'base_model.features.6.1.block.1.0 (Conv2d)') ,
    (BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.1.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.1.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.6.1.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.6.1.block.2.fc1 (Conv2d)') ,
    (Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.6.1.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.1.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.6.1.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(1152, 192, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.6.1.block.3.0 (Conv2d)') ,
    (BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.1.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.15000000000000002, mode='row'), 'base_model.features.6.1.stochastic_depth (StochasticDepth)') ,
    (Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.6.2.block.0.0 (Conv2d)') ,
    (BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.2.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.2.block.0.2 (SiLU)') ,
    (Conv2d(1152, 1152, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=1152, bias=False), 'base_model.features.6.2.block.1.0 (Conv2d)') ,
    (BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.2.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.2.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.6.2.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.6.2.block.2.fc1 (Conv2d)') ,
    (Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.6.2.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.2.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.6.2.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(1152, 192, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.6.2.block.3.0 (Conv2d)') ,
    (BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.2.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.1625, mode='row'), 'base_model.features.6.2.stochastic_depth (StochasticDepth)') ,
    (Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.6.3.block.0.0 (Conv2d)') ,
    (BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.3.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.3.block.0.2 (SiLU)') ,
    (Conv2d(1152, 1152, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=1152, bias=False), 'base_model.features.6.3.block.1.0 (Conv2d)') ,
    (BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.3.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.3.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.6.3.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.6.3.block.2.fc1 (Conv2d)') ,
    (Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.6.3.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.3.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.6.3.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(1152, 192, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.6.3.block.3.0 (Conv2d)') ,
    (BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.3.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.17500000000000002, mode='row'), 'base_model.features.6.3.stochastic_depth (StochasticDepth)') ,
    (Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.7.0.block.0.0 (Conv2d)') ,
    (BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.7.0.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.7.0.block.0.2 (SiLU)') ,
    (Conv2d(1152, 1152, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=1152, bias=False), 'base_model.features.7.0.block.1.0 (Conv2d)') ,
    (BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.7.0.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.7.0.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.7.0.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.7.0.block.2.fc1 (Conv2d)') ,
    (Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.7.0.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.7.0.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.7.0.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(1152, 320, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.7.0.block.3.0 (Conv2d)') ,
    (BatchNorm2d(320, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.7.0.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.1875, mode='row'), 'base_model.features.7.0.stochastic_depth (StochasticDepth)') ,
    (Conv2d(320, 1280, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.8.0 (Conv2d)') ,
    (BatchNorm2d(1280, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.8.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.8.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.avgpool (AdaptiveAvgPool2d)') ,
    (Dropout(p=0.2, inplace=True), 'base_model.classifier.0 (Dropout)') ,
    (Linear(in_features=1280, out_features=1000, bias=True), 'base_model.classifier.1 (Linear)') ,
    (AdaptiveAvgPool2d(output_size=1), 'pooling (AdaptiveAvgPool2d)') ,
    (Linear(in_features=1280, out_features=128, bias=True), 'fc1 (Linear)') ,
    (ReLU(), 'relu (ReLU)') ,
    (Linear(in_features=128, out_features=53, bias=True), 'fc2 (Linear)') ,
    (Softmax(dim=1), 'softmax (Softmax)') ,
]

efficientnet2_layers = [
    (Conv2d(3, 32, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), bias=False), 'base_model.features.0.0 (Conv2d)') ,
    (BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.0.2 (SiLU)') ,
    (Conv2d(32, 32, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=32, bias=False), 'base_model.features.1.0.block.0.0 (Conv2d)') ,
    (BatchNorm2d(32, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.1.0.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.1.0.block.0.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.1.0.block.1.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(32, 8, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.1.0.block.1.fc1 (Conv2d)') ,
    (Conv2d(8, 32, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.1.0.block.1.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.1.0.block.1.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.1.0.block.1.scale_activation (Sigmoid)') ,
    (Conv2d(32, 16, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.1.0.block.2.0 (Conv2d)') ,
    (BatchNorm2d(16, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.1.0.block.2.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.0, mode='row'), 'base_model.features.1.0.stochastic_depth (StochasticDepth)') ,
    (Conv2d(16, 96, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.2.0.block.0.0 (Conv2d)') ,
    (BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.2.0.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.2.0.block.0.2 (SiLU)') ,
    (Conv2d(96, 96, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=96, bias=False), 'base_model.features.2.0.block.1.0 (Conv2d)') ,
    (BatchNorm2d(96, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.2.0.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.2.0.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.2.0.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(96, 4, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.2.0.block.2.fc1 (Conv2d)') ,
    (Conv2d(4, 96, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.2.0.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.2.0.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.2.0.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(96, 24, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.2.0.block.3.0 (Conv2d)') ,
    (BatchNorm2d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.2.0.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.0125, mode='row'), 'base_model.features.2.0.stochastic_depth (StochasticDepth)') ,
    (Conv2d(24, 144, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.2.1.block.0.0 (Conv2d)') ,
    (BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.2.1.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.2.1.block.0.2 (SiLU)') ,
    (Conv2d(144, 144, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=144, bias=False), 'base_model.features.2.1.block.1.0 (Conv2d)') ,
    (BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.2.1.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.2.1.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.2.1.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(144, 6, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.2.1.block.2.fc1 (Conv2d)') ,
    (Conv2d(6, 144, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.2.1.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.2.1.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.2.1.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(144, 24, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.2.1.block.3.0 (Conv2d)') ,
    (BatchNorm2d(24, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.2.1.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.025, mode='row'), 'base_model.features.2.1.stochastic_depth (StochasticDepth)') ,
    (Conv2d(24, 144, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.3.0.block.0.0 (Conv2d)') ,
    (BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.3.0.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.3.0.block.0.2 (SiLU)') ,
    (Conv2d(144, 144, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2), groups=144, bias=False), 'base_model.features.3.0.block.1.0 (Conv2d)') ,
    (BatchNorm2d(144, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.3.0.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.3.0.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.3.0.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(144, 6, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.3.0.block.2.fc1 (Conv2d)') ,
    (Conv2d(6, 144, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.3.0.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.3.0.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.3.0.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(144, 40, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.3.0.block.3.0 (Conv2d)') ,
    (BatchNorm2d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.3.0.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.037500000000000006, mode='row'), 'base_model.features.3.0.stochastic_depth (StochasticDepth)') ,
    (Conv2d(40, 240, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.3.1.block.0.0 (Conv2d)') ,
    (BatchNorm2d(240, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.3.1.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.3.1.block.0.2 (SiLU)') ,
    (Conv2d(240, 240, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=240, bias=False), 'base_model.features.3.1.block.1.0 (Conv2d)') ,
    (BatchNorm2d(240, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.3.1.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.3.1.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.3.1.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(240, 10, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.3.1.block.2.fc1 (Conv2d)') ,
    (Conv2d(10, 240, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.3.1.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.3.1.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.3.1.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(240, 40, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.3.1.block.3.0 (Conv2d)') ,
    (BatchNorm2d(40, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.3.1.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.05, mode='row'), 'base_model.features.3.1.stochastic_depth (StochasticDepth)') ,
    (Conv2d(40, 240, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.4.0.block.0.0 (Conv2d)') ,
    (BatchNorm2d(240, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.0.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.0.block.0.2 (SiLU)') ,
    (Conv2d(240, 240, kernel_size=(3, 3), stride=(2, 2), padding=(1, 1), groups=240, bias=False), 'base_model.features.4.0.block.1.0 (Conv2d)') ,
    (BatchNorm2d(240, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.0.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.0.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.4.0.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(240, 10, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.4.0.block.2.fc1 (Conv2d)') ,
    (Conv2d(10, 240, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.4.0.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.0.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.4.0.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(240, 80, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.4.0.block.3.0 (Conv2d)') ,
    (BatchNorm2d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.0.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.0625, mode='row'), 'base_model.features.4.0.stochastic_depth (StochasticDepth)') ,
    (Conv2d(80, 480, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.4.1.block.0.0 (Conv2d)') ,
    (BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.1.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.1.block.0.2 (SiLU)') ,
    (Conv2d(480, 480, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=480, bias=False), 'base_model.features.4.1.block.1.0 (Conv2d)') ,
    (BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.1.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.1.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.4.1.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(480, 20, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.4.1.block.2.fc1 (Conv2d)') ,
    (Conv2d(20, 480, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.4.1.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.1.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.4.1.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(480, 80, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.4.1.block.3.0 (Conv2d)') ,
    (BatchNorm2d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.1.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.07500000000000001, mode='row'), 'base_model.features.4.1.stochastic_depth (StochasticDepth)') ,
    (Conv2d(80, 480, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.4.2.block.0.0 (Conv2d)') ,
    (BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.2.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.2.block.0.2 (SiLU)') ,
    (Conv2d(480, 480, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=480, bias=False), 'base_model.features.4.2.block.1.0 (Conv2d)') ,
    (BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.2.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.2.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.4.2.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(480, 20, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.4.2.block.2.fc1 (Conv2d)') ,
    (Conv2d(20, 480, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.4.2.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.4.2.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.4.2.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(480, 80, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.4.2.block.3.0 (Conv2d)') ,
    (BatchNorm2d(80, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.4.2.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.08750000000000001, mode='row'), 'base_model.features.4.2.stochastic_depth (StochasticDepth)') ,
    (Conv2d(80, 480, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.5.0.block.0.0 (Conv2d)') ,
    (BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.0.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.0.block.0.2 (SiLU)') ,
    (Conv2d(480, 480, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=480, bias=False), 'base_model.features.5.0.block.1.0 (Conv2d)') ,
    (BatchNorm2d(480, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.0.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.0.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.5.0.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(480, 20, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.5.0.block.2.fc1 (Conv2d)') ,
    (Conv2d(20, 480, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.5.0.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.0.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.5.0.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(480, 112, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.5.0.block.3.0 (Conv2d)') ,
    (BatchNorm2d(112, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.0.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.1, mode='row'), 'base_model.features.5.0.stochastic_depth (StochasticDepth)') ,
    (Conv2d(112, 672, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.5.1.block.0.0 (Conv2d)') ,
    (BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.1.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.1.block.0.2 (SiLU)') ,
    (Conv2d(672, 672, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=672, bias=False), 'base_model.features.5.1.block.1.0 (Conv2d)') ,
    (BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.1.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.1.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.5.1.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(672, 28, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.5.1.block.2.fc1 (Conv2d)') ,
    (Conv2d(28, 672, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.5.1.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.1.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.5.1.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(672, 112, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.5.1.block.3.0 (Conv2d)') ,
    (BatchNorm2d(112, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.1.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.1125, mode='row'), 'base_model.features.5.1.stochastic_depth (StochasticDepth)') ,
    (Conv2d(112, 672, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.5.2.block.0.0 (Conv2d)') ,
    (BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.2.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.2.block.0.2 (SiLU)') ,
    (Conv2d(672, 672, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=672, bias=False), 'base_model.features.5.2.block.1.0 (Conv2d)') ,
    (BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.2.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.2.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.5.2.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(672, 28, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.5.2.block.2.fc1 (Conv2d)') ,
    (Conv2d(28, 672, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.5.2.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.5.2.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.5.2.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(672, 112, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.5.2.block.3.0 (Conv2d)') ,
    (BatchNorm2d(112, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.5.2.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.125, mode='row'), 'base_model.features.5.2.stochastic_depth (StochasticDepth)') ,
    (Conv2d(112, 672, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.6.0.block.0.0 (Conv2d)') ,
    (BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.0.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.0.block.0.2 (SiLU)') ,
    (Conv2d(672, 672, kernel_size=(5, 5), stride=(2, 2), padding=(2, 2), groups=672, bias=False), 'base_model.features.6.0.block.1.0 (Conv2d)') ,
    (BatchNorm2d(672, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.0.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.0.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.6.0.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(672, 28, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.6.0.block.2.fc1 (Conv2d)') ,
    (Conv2d(28, 672, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.6.0.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.0.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.6.0.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(672, 192, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.6.0.block.3.0 (Conv2d)') ,
    (BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.0.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.1375, mode='row'), 'base_model.features.6.0.stochastic_depth (StochasticDepth)') ,
    (Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.6.1.block.0.0 (Conv2d)') ,
    (BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.1.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.1.block.0.2 (SiLU)') ,
    (Conv2d(1152, 1152, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=1152, bias=False), 'base_model.features.6.1.block.1.0 (Conv2d)') ,
    (BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.1.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.1.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.6.1.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.6.1.block.2.fc1 (Conv2d)') ,
    (Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.6.1.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.1.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.6.1.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(1152, 192, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.6.1.block.3.0 (Conv2d)') ,
    (BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.1.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.15000000000000002, mode='row'), 'base_model.features.6.1.stochastic_depth (StochasticDepth)') ,
    (Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.6.2.block.0.0 (Conv2d)') ,
    (BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.2.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.2.block.0.2 (SiLU)') ,
    (Conv2d(1152, 1152, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=1152, bias=False), 'base_model.features.6.2.block.1.0 (Conv2d)') ,
    (BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.2.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.2.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.6.2.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.6.2.block.2.fc1 (Conv2d)') ,
    (Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.6.2.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.2.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.6.2.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(1152, 192, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.6.2.block.3.0 (Conv2d)') ,
    (BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.2.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.1625, mode='row'), 'base_model.features.6.2.stochastic_depth (StochasticDepth)') ,
    (Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.6.3.block.0.0 (Conv2d)') ,
    (BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.3.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.3.block.0.2 (SiLU)') ,
    (Conv2d(1152, 1152, kernel_size=(5, 5), stride=(1, 1), padding=(2, 2), groups=1152, bias=False), 'base_model.features.6.3.block.1.0 (Conv2d)') ,
    (BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.3.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.3.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.6.3.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.6.3.block.2.fc1 (Conv2d)') ,
    (Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.6.3.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.6.3.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.6.3.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(1152, 192, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.6.3.block.3.0 (Conv2d)') ,
    (BatchNorm2d(192, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.6.3.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.17500000000000002, mode='row'), 'base_model.features.6.3.stochastic_depth (StochasticDepth)') ,
    (Conv2d(192, 1152, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.7.0.block.0.0 (Conv2d)') ,
    (BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.7.0.block.0.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.7.0.block.0.2 (SiLU)') ,
    (Conv2d(1152, 1152, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), groups=1152, bias=False), 'base_model.features.7.0.block.1.0 (Conv2d)') ,
    (BatchNorm2d(1152, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.7.0.block.1.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.7.0.block.1.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.features.7.0.block.2.avgpool (AdaptiveAvgPool2d)') ,
    (Conv2d(1152, 48, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.7.0.block.2.fc1 (Conv2d)') ,
    (Conv2d(48, 1152, kernel_size=(1, 1), stride=(1, 1)), 'base_model.features.7.0.block.2.fc2 (Conv2d)') ,
    (SiLU(inplace=True), 'base_model.features.7.0.block.2.activation (SiLU)') ,
    (Sigmoid(), 'base_model.features.7.0.block.2.scale_activation (Sigmoid)') ,
    (Conv2d(1152, 320, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.7.0.block.3.0 (Conv2d)') ,
    (BatchNorm2d(320, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.7.0.block.3.1 (BatchNorm2d)') ,
    (StochasticDepth(p=0.1875, mode='row'), 'base_model.features.7.0.stochastic_depth (StochasticDepth)') ,
    (Conv2d(320, 1280, kernel_size=(1, 1), stride=(1, 1), bias=False), 'base_model.features.8.0 (Conv2d)') ,
    (BatchNorm2d(1280, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'base_model.features.8.1 (BatchNorm2d)') ,
    (SiLU(inplace=True), 'base_model.features.8.2 (SiLU)') ,
    (AdaptiveAvgPool2d(output_size=1), 'base_model.avgpool (AdaptiveAvgPool2d)') ,
    (Dropout(p=0.2, inplace=True), 'base_model.classifier.0 (Dropout)') ,
    (Linear(in_features=1280, out_features=1000, bias=True), 'base_model.classifier.1 (Linear)') ,
    (AdaptiveAvgPool2d(output_size=1), 'pooling (AdaptiveAvgPool2d)') ,
    (BatchNorm1d(128, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True), 'batch_norm (BatchNorm1d)') ,
    (Linear(in_features=1280, out_features=128, bias=True), 'fc1 (Linear)') ,
    (ReLU(), 'relu (ReLU)') ,
    (Linear(in_features=128, out_features=53, bias=True), 'fc2 (Linear)') ,
    (Softmax(dim=1), 'softmax (Softmax)') ,
]

